
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v5.3  Build: 5.3.1
-- MySql DDL Script generated from project: Tournament-DAL
-- Project filename: D:\Internet\Websites\volleyball-turnier.de\DAL\TournamentCalendar-DAL.llblgenproj
-- Script generated on: 22-Apr-2018 16:58.26
--
-- This is a Create script for creating a NEW data model. If you want DDL SQL for updating an existing model,
-- please create an Update script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime. Schemas aren't dropped in the DROP section.
--
--      >>>>> WARNING <<<<<
--      This is a CREATE script, with DROP statements for the existing tables, foreign keys and other constraints
--      This means that existing tables, data, constraints and other elements in the catalog/schemas addressed
--      are deleted. Use this Create script only to create new schemas with tables/constraints and other elements.
--
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- DROP statements for existing elements. 
-- ###############################################################################################################
-- DROP statements for dropping existing elements with the same names as the ones created are commented out below. 
-- If you want to enable these statements for DROPping the existing elements first (which will remove all the data
-- in these existing elements), uncomment these statements by removing the two comment markers /* and */

-- Remove the comment marker on the NEXT line to enable DROP statements to remove existing elements
/* 

USE dbvbc01;
-- ----------------------------------------------------------------------------------------------------------------
-- DROP Foreign keys
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE `vbt_calendar` DROP FOREIGN KEY `Fk_PlayingAbilityFrom`;

ALTER TABLE `vbt_calendar` DROP FOREIGN KEY `Fk_PlayingAbilityTo`;

ALTER TABLE `vbt_calendar` DROP FOREIGN KEY `Fk_Surface`;

ALTER TABLE `vbt_calendar` DROP FOREIGN KEY `Fk_Tournament_Country`;

ALTER TABLE `vbt_info_service` DROP FOREIGN KEY `Fk_Vbc_InfoService_Country`;
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'Default' 
-- ----------------------------------------------------------------------------------------------------------------

DROP TABLE `vbt_calendar`;

DROP TABLE `vbt_country`;

DROP TABLE `vbt_info_service`;

DROP TABLE `vbt_playing_ability`;

DROP TABLE `vbt_surface`;
*/
-- Remove the comment marker on the PREVIOUS line to enable DROP statements to remove existing elements

-- ###############################################################################################################
-- Create statements for catalogs, schemas, tables and sequences
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'dbvbc01'
-- ----------------------------------------------------------------------------------------------------------------


USE dbvbc01;
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'Default'
-- ----------------------------------------------------------------------------------------------------------------

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE `vbt_calendar`
(
    `Id` Int UNSIGNED AUTO_INCREMENT NOT NULL, 
    `Guid` VarChar(50) NULL, 
    `TournamentName` VarChar(255) NOT NULL, 
    `DateFrom` DateTime NOT NULL, 
    `DateTo` DateTime NOT NULL, 
    `ClosingDate` Date NOT NULL, 
    `Venue` VarChar(100) NULL, 
    `CountryId` Char(2) NOT NULL, 
    `PostalCode` VarChar(10) NULL, 
    `City` VarChar(100) NULL, 
    `Street` VarChar(100) NULL, 
    `Longitude` Double NULL, 
    `Latitude` Double NULL, 
    `NumOfTeams` Integer NOT NULL, 
    `NumPlayersMale` Integer NOT NULL, 
    `IsMinPlayersMale` TinyInt NOT NULL, 
    `NumPlayersFemale` Integer NOT NULL, 
    `IsMinPlayersFemale` TinyInt NOT NULL, 
    `Surface` Int UNSIGNED NOT NULL, 
    `PlayingAbilityFrom` Int UNSIGNED NOT NULL, 
    `PlayingAbilityTo` Int UNSIGNED NOT NULL, 
    `EntryFee` Decimal(5, 2) NOT NULL, 
    `Bond` Decimal(5, 2) NOT NULL, 
    `Info` VarChar(1024) NULL, 
    `Organizer` VarChar(255) NULL, 
    `ContactAddress` VarChar(1024) NULL, 
    `Email` VarChar(255) NULL, 
    `Website` VarChar(255) NULL, 
    `PostedByName` VarChar(50) NULL, 
    `PostedByEmail` VarChar(255) NULL, 
    `PostedByPassword` VarChar(64) NULL, 
    `AttachmentFile` VarChar(512) NULL, 
    `Special` VarChar(512) NULL, 
    `CreatedOn` DateTime NOT NULL, 
    `ModifiedOn` Timestamp NOT NULL, 
    `DeletedOn` DateTime NULL, 
    `ApprovedOn` DateTime NULL
    , KEY(Id)
);

CREATE TABLE `vbt_country`
(
    `Id` Char(2) NOT NULL, 
    `Iso3` Char(3) NOT NULL, 
    `Name` VarChar(255) NOT NULL, 
    `CreatedOn` DateTime NOT NULL, 
    `ModifiedOn` Timestamp NOT NULL
);

CREATE TABLE `vbt_info_service`
(
    `Id` Integer AUTO_INCREMENT NOT NULL, 
    `TeamName` VarChar(255) NOT NULL, 
    `ClubName` VarChar(255) NOT NULL, 
    `Gender` VarChar(50) NOT NULL, 
    `Title` VarChar(30) NOT NULL, 
    `FirstName` VarChar(50) NOT NULL, 
    `LastName` VarChar(50) NOT NULL, 
    `Nickname` VarChar(50) NOT NULL, 
    `CountryId` Char(2) NULL, 
    `ZipCode` VarChar(6) NOT NULL, 
    `City` VarChar(50) NOT NULL, 
    `Street` VarChar(255) NOT NULL, 
    `Longitude` Double NULL, 
    `Latitude` Double NULL, 
    `MaxDistance` Integer NULL, 
    `Email` VarChar(50) NOT NULL, 
    `UserName` VarChar(50) NOT NULL, 
    `UserPassword` VarChar(10) NOT NULL, 
    `Guid` VarChar(64) NULL, 
    `Comments` VarChar(255) NOT NULL, 
    `SubscribedOn` DateTime NOT NULL, 
    `ModifiedOn` Timestamp NOT NULL, 
    `ConfirmedOn` DateTime NULL, 
    `UnSubscribedOn` DateTime NULL
    , KEY(Id)
);

CREATE TABLE `vbt_playing_ability`
(
    `Id` Int UNSIGNED AUTO_INCREMENT NOT NULL, 
    `Strength` Int UNSIGNED NOT NULL, 
    `Description` VarChar(255) NOT NULL, 
    `CreatedOn` DateTime NOT NULL, 
    `ModifiedOn` Timestamp NOT NULL
    , KEY(Id)
);

CREATE TABLE `vbt_surface`
(
    `Id` Int UNSIGNED AUTO_INCREMENT NOT NULL, 
    `Description` VarChar(255) NOT NULL, 
    `CreatedOn` DateTime NOT NULL, 
    `ModifiedOn` Timestamp NOT NULL
    , KEY(Id)
);

-- ###############################################################################################################
-- Create statements for Primary key constraints, Foreign key constraints, Unique constraints and Default Values
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'dbvbc01'
-- ----------------------------------------------------------------------------------------------------------------

USE dbvbc01;
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'Default'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE `vbt_calendar`
    ADD CONSTRAINT `` PRIMARY KEY
    ( 
        `Id` 
    );

ALTER TABLE `vbt_country`
    ADD CONSTRAINT `` PRIMARY KEY
    ( 
        `Id` 
    );

ALTER TABLE `vbt_info_service`
    ADD CONSTRAINT `` PRIMARY KEY
    ( 
        `Id` 
    );

ALTER TABLE `vbt_playing_ability`
    ADD CONSTRAINT `` PRIMARY KEY
    ( 
        `Strength` 
    );

ALTER TABLE `vbt_surface`
    ADD CONSTRAINT `` PRIMARY KEY
    ( 
        `Id` 
    );
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'Default'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE `vbt_country`
    ADD CONSTRAINT "Id" UNIQUE
    (
        `Id` 
    );


ALTER TABLE `vbt_country`
    ADD CONSTRAINT "Iso3" UNIQUE
    (
        `Iso3` 
    );


ALTER TABLE `vbt_info_service`
    ADD CONSTRAINT "Guid_2" UNIQUE
    (
         
    );


ALTER TABLE `vbt_playing_ability`
    ADD CONSTRAINT "Id" UNIQUE
    (
        `Id` 
    );


ALTER TABLE `vbt_surface`
    ADD CONSTRAINT "Id" UNIQUE
    (
        `Id` 
    );

-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'Default'
-- ----------------------------------------------------------------------------------------------------------------
ALTER TABLE `vbt_calendar`
	ALTER COLUMN `NumOfTeams` SET DEFAULT 0;
ALTER TABLE `vbt_calendar`
	ALTER COLUMN `IsMinPlayersMale` SET DEFAULT 0;
ALTER TABLE `vbt_calendar`
	ALTER COLUMN `IsMinPlayersFemale` SET DEFAULT 0;
ALTER TABLE `vbt_calendar`
	ALTER COLUMN `Surface` SET DEFAULT 1;
ALTER TABLE `vbt_calendar`
	ALTER COLUMN `PlayingAbilityFrom` SET DEFAULT 0;
ALTER TABLE `vbt_calendar`
	ALTER COLUMN `PlayingAbilityTo` SET DEFAULT 0;
ALTER TABLE `vbt_calendar`
	ALTER COLUMN `ModifiedOn` SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `vbt_country`
	ALTER COLUMN `ModifiedOn` SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `vbt_info_service`
	ALTER COLUMN `Gender` SET DEFAULT 'm';
ALTER TABLE `vbt_info_service`
	ALTER COLUMN `ModifiedOn` SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `vbt_playing_ability`
	ALTER COLUMN `Strength` SET DEFAULT 0;
ALTER TABLE `vbt_playing_ability`
	ALTER COLUMN `ModifiedOn` SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `vbt_surface`
	ALTER COLUMN `ModifiedOn` SET DEFAULT CURRENT_TIMESTAMP;
-- ----------------------------------------------------------------------------------------------------------------
-- All foreign Key constraints
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE `vbt_calendar` 
    ADD CONSTRAINT `Fk_PlayingAbilityFrom` FOREIGN KEY
    (
        `PlayingAbilityFrom` 
    )
    REFERENCES `vbt_playing_ability`
    (
        `Strength` 
    );

ALTER TABLE `vbt_calendar` 
    ADD CONSTRAINT `Fk_PlayingAbilityTo` FOREIGN KEY
    (
        `PlayingAbilityTo` 
    )
    REFERENCES `vbt_playing_ability`
    (
        `Strength` 
    );

ALTER TABLE `vbt_calendar` 
    ADD CONSTRAINT `Fk_Surface` FOREIGN KEY
    (
        `Surface` 
    )
    REFERENCES `vbt_surface`
    (
        `Id` 
    );

ALTER TABLE `vbt_calendar` 
    ADD CONSTRAINT `Fk_Tournament_Country` FOREIGN KEY
    (
        `CountryId` 
    )
    REFERENCES `vbt_country`
    (
        `Id` 
    );

ALTER TABLE `vbt_info_service` 
    ADD CONSTRAINT `Fk_Vbc_InfoService_Country` FOREIGN KEY
    (
        `CountryId` 
    )
    REFERENCES `vbt_country`
    (
        `Id` 
    );
