//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using TournamentCalendarDAL.EntityClasses;
using TournamentCalendarDAL.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace TournamentCalendarDAL.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the Calendar entity</summary>
		public EntityQuery<CalendarEntity> Calendar { get { return Create<CalendarEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Country entity</summary>
		public EntityQuery<CountryEntity> Country { get { return Create<CountryEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the InfoService entity</summary>
		public EntityQuery<InfoServiceEntity> InfoService { get { return Create<InfoServiceEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the PlayingAbility entity</summary>
		public EntityQuery<PlayingAbilityEntity> PlayingAbility { get { return Create<PlayingAbilityEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the SentNewsletter entity</summary>
		public EntityQuery<SentNewsletterEntity> SentNewsletter { get { return Create<SentNewsletterEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Surface entity</summary>
		public EntityQuery<SurfaceEntity> Surface { get { return Create<SurfaceEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}