//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using TournamentCalendarDAL.FactoryClasses;
using TournamentCalendarDAL.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace TournamentCalendarDAL.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCalendarEntityInfo();
			InitCountryEntityInfo();
			InitInfoServiceEntityInfo();
			InitPlayingAbilityEntityInfo();
			InitSentNewsletterEntityInfo();
			InitSurfaceEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits CalendarEntity's info objects</summary>
		private void InitCalendarEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CalendarFieldIndex), "CalendarEntity");
			this.AddElementFieldInfo("CalendarEntity", "ApprovedOn", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CalendarFieldIndex.ApprovedOn, 0, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "AttachmentFile", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.AttachmentFile, 512, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "Bond", typeof(System.Decimal), false, false, false, false,  (int)CalendarFieldIndex.Bond, 0, 2, 5);
			this.AddElementFieldInfo("CalendarEntity", "City", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.City, 100, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "ClosingDate", typeof(System.DateTime), false, false, false, false,  (int)CalendarFieldIndex.ClosingDate, 0, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "ContactAddress", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.ContactAddress, 1024, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "CountryId", typeof(System.String), false, true, false, false,  (int)CalendarFieldIndex.CountryId, 2, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "CreatedByUser", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.CreatedByUser, 50, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)CalendarFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "DateFrom", typeof(System.DateTime), false, false, false, false,  (int)CalendarFieldIndex.DateFrom, 0, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "DateTo", typeof(System.DateTime), false, false, false, false,  (int)CalendarFieldIndex.DateTo, 0, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "DeletedOn", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CalendarFieldIndex.DeletedOn, 0, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "Email", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.Email, 255, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "EntryFee", typeof(System.Decimal), false, false, false, false,  (int)CalendarFieldIndex.EntryFee, 0, 2, 5);
			this.AddElementFieldInfo("CalendarEntity", "Guid", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.Guid, 50, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)CalendarFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("CalendarEntity", "Info", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.Info, 1024, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "IsMinPlayersFemale", typeof(System.Boolean), false, false, false, false,  (int)CalendarFieldIndex.IsMinPlayersFemale, 0, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "IsMinPlayersMale", typeof(System.Boolean), false, false, false, false,  (int)CalendarFieldIndex.IsMinPlayersMale, 0, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "Latitude", typeof(Nullable<System.Double>), false, false, false, true,  (int)CalendarFieldIndex.Latitude, 0, 0, 38);
			this.AddElementFieldInfo("CalendarEntity", "Longitude", typeof(Nullable<System.Double>), false, false, false, true,  (int)CalendarFieldIndex.Longitude, 0, 0, 38);
			this.AddElementFieldInfo("CalendarEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)CalendarFieldIndex.ModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "NumOfTeams", typeof(System.Int32), false, false, false, false,  (int)CalendarFieldIndex.NumOfTeams, 0, 0, 10);
			this.AddElementFieldInfo("CalendarEntity", "NumPlayersFemale", typeof(System.Int32), false, false, false, false,  (int)CalendarFieldIndex.NumPlayersFemale, 0, 0, 10);
			this.AddElementFieldInfo("CalendarEntity", "NumPlayersMale", typeof(System.Int32), false, false, false, false,  (int)CalendarFieldIndex.NumPlayersMale, 0, 0, 10);
			this.AddElementFieldInfo("CalendarEntity", "Organizer", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.Organizer, 255, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "PlayingAbilityFrom", typeof(System.Int64), false, true, false, false,  (int)CalendarFieldIndex.PlayingAbilityFrom, 0, 0, 19);
			this.AddElementFieldInfo("CalendarEntity", "PlayingAbilityTo", typeof(System.Int64), false, true, false, false,  (int)CalendarFieldIndex.PlayingAbilityTo, 0, 0, 19);
			this.AddElementFieldInfo("CalendarEntity", "PostalCode", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.PostalCode, 10, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "PostedByEmail", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.PostedByEmail, 255, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "PostedByName", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.PostedByName, 50, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "PostedByPassword", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.PostedByPassword, 64, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "Special", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.Special, 512, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "Street", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.Street, 100, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "Surface", typeof(System.Int64), false, true, false, false,  (int)CalendarFieldIndex.Surface, 0, 0, 19);
			this.AddElementFieldInfo("CalendarEntity", "TournamentName", typeof(System.String), false, false, false, false,  (int)CalendarFieldIndex.TournamentName, 255, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "Venue", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.Venue, 100, 0, 0);
			this.AddElementFieldInfo("CalendarEntity", "Website", typeof(System.String), false, false, false, true,  (int)CalendarFieldIndex.Website, 255, 0, 0);
		}

		/// <summary>Inits CountryEntity's info objects</summary>
		private void InitCountryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CountryFieldIndex), "CountryEntity");
			this.AddElementFieldInfo("CountryEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)CountryFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("CountryEntity", "Id", typeof(System.String), true, false, false, false,  (int)CountryFieldIndex.Id, 2, 0, 0);
			this.AddElementFieldInfo("CountryEntity", "Iso3", typeof(System.String), false, false, false, false,  (int)CountryFieldIndex.Iso3, 3, 0, 0);
			this.AddElementFieldInfo("CountryEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)CountryFieldIndex.ModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("CountryEntity", "Name", typeof(System.String), false, false, false, false,  (int)CountryFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("CountryEntity", "NameEn", typeof(System.String), false, false, false, false,  (int)CountryFieldIndex.NameEn, 255, 0, 0);
		}

		/// <summary>Inits InfoServiceEntity's info objects</summary>
		private void InitInfoServiceEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(InfoServiceFieldIndex), "InfoServiceEntity");
			this.AddElementFieldInfo("InfoServiceEntity", "City", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.City, 50, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "Comments", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.Comments, 255, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "ConfirmedOn", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)InfoServiceFieldIndex.ConfirmedOn, 0, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "CountryId", typeof(System.String), false, true, false, true,  (int)InfoServiceFieldIndex.CountryId, 2, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "Email", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.Email, 50, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.FirstName, 50, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "Gender", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.Gender, 50, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "Guid", typeof(System.String), false, false, false, true,  (int)InfoServiceFieldIndex.Guid, 64, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)InfoServiceFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("InfoServiceEntity", "LastName", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.LastName, 50, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "Latitude", typeof(Nullable<System.Double>), false, false, false, true,  (int)InfoServiceFieldIndex.Latitude, 0, 0, 38);
			this.AddElementFieldInfo("InfoServiceEntity", "Longitude", typeof(Nullable<System.Double>), false, false, false, true,  (int)InfoServiceFieldIndex.Longitude, 0, 0, 38);
			this.AddElementFieldInfo("InfoServiceEntity", "MaxDistance", typeof(Nullable<System.Int32>), false, false, false, true,  (int)InfoServiceFieldIndex.MaxDistance, 0, 0, 10);
			this.AddElementFieldInfo("InfoServiceEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)InfoServiceFieldIndex.ModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "Street", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.Street, 255, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "SubscribedOn", typeof(System.DateTime), false, false, false, false,  (int)InfoServiceFieldIndex.SubscribedOn, 0, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "Title", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.Title, 30, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "UserName", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.UserName, 50, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "UserPassword", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.UserPassword, 50, 0, 0);
			this.AddElementFieldInfo("InfoServiceEntity", "ZipCode", typeof(System.String), false, false, false, false,  (int)InfoServiceFieldIndex.ZipCode, 6, 0, 0);
		}

		/// <summary>Inits PlayingAbilityEntity's info objects</summary>
		private void InitPlayingAbilityEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PlayingAbilityFieldIndex), "PlayingAbilityEntity");
			this.AddElementFieldInfo("PlayingAbilityEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)PlayingAbilityFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("PlayingAbilityEntity", "Description", typeof(System.String), false, false, false, false,  (int)PlayingAbilityFieldIndex.Description, 255, 0, 0);
			this.AddElementFieldInfo("PlayingAbilityEntity", "Id", typeof(System.Int64), false, false, true, false,  (int)PlayingAbilityFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("PlayingAbilityEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)PlayingAbilityFieldIndex.ModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("PlayingAbilityEntity", "Strength", typeof(System.Int64), true, false, false, false,  (int)PlayingAbilityFieldIndex.Strength, 0, 0, 19);
		}

		/// <summary>Inits SentNewsletterEntity's info objects</summary>
		private void InitSentNewsletterEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SentNewsletterFieldIndex), "SentNewsletterEntity");
			this.AddElementFieldInfo("SentNewsletterEntity", "CompletedOn", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)SentNewsletterFieldIndex.CompletedOn, 0, 0, 0);
			this.AddElementFieldInfo("SentNewsletterEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)SentNewsletterFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("SentNewsletterEntity", "NumOfRecipients", typeof(System.Int32), false, false, false, false,  (int)SentNewsletterFieldIndex.NumOfRecipients, 0, 0, 10);
			this.AddElementFieldInfo("SentNewsletterEntity", "NumOfTournaments", typeof(System.Int32), false, false, false, false,  (int)SentNewsletterFieldIndex.NumOfTournaments, 0, 0, 10);
			this.AddElementFieldInfo("SentNewsletterEntity", "StartedOn", typeof(System.DateTime), false, false, false, false,  (int)SentNewsletterFieldIndex.StartedOn, 0, 0, 0);
		}

		/// <summary>Inits SurfaceEntity's info objects</summary>
		private void InitSurfaceEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SurfaceFieldIndex), "SurfaceEntity");
			this.AddElementFieldInfo("SurfaceEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)SurfaceFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("SurfaceEntity", "Description", typeof(System.String), false, false, false, false,  (int)SurfaceFieldIndex.Description, 255, 0, 0);
			this.AddElementFieldInfo("SurfaceEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)SurfaceFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("SurfaceEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)SurfaceFieldIndex.ModifiedOn, 0, 0, 0);
		}
	}
}