//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace TournamentCalendarDAL
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Calendar</summary>
		CalendarEntity,
		///<summary>Country</summary>
		CountryEntity,
		///<summary>InfoService</summary>
		InfoServiceEntity,
		///<summary>PlayingAbility</summary>
		PlayingAbilityEntity,
		///<summary>SentNewsletter</summary>
		SentNewsletterEntity,
		///<summary>Surface</summary>
		SurfaceEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

