name: build + test

on:
  push:
    branches: [ main, 'version/**', 'pr/**', 'pr-**' ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main, 'version/**', 'pr/**', 'pr-**' ]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Src/TournamentCalendar.sln
    - name: Build
      run: dotnet build ./Src/TournamentCalendar.sln --no-restore /p:configuration=release -p:EnvironmentName=Production
